### ISSUE TITLE
Question about port binding for docker

### ISSUE THREAD

**Issue by palidanx** [banool/codenames-pictures#34]
I'm trying to build the repo for docker

```
FROM alpine:latest

RUN apk add --no-cache git make musl-dev go

# Configure Go
ENV GOROOT /usr/lib/go
ENV GOPATH /go
ENV PATH /go/bin:$PATH

RUN mkdir -p ${GOPATH}/src ${GOPATH}/bin

WORKDIR $GOPATH
RUN go get github.com/banool/codenames-pictures/...
RUN go install github.com/banool/codenames-pictures/...


WORKDIR $GOPATH/bin
RUN ln -s ../src/github.com/banool/codenames-pictures/assets_codenames
EXPOSE 9090
RUN ./codenames 9090
```

docker-compose.yml
```
version: '3'

services:
  codenames:
    container_name: codenames
    ports:
        - "0.0.0.0:9090:9090" 
    build:
      context: .
      dockerfile: ./codenames/Dockerfile
    restart: always
    networks:
      - main
networks:
  main:
    driver: bridge  
```

My main question is when you run:
`RUN ./codenames 9090`

Does that expose it to all interfaces (namely `0.0.0.0`)?  I'm trying to access the site via
`http://127.0.0.1:9090` and it can't connect and I'm trying to figure out why
